package ru.idc.labgatej.drivers.DNATechnologyDriver.entities.symphony.rack;


import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@Data
public class RackPosition
{
    /**
     * Sample ID (read by the bar code scanner from a rack file or entered
     * manually), or name of the extraction control, assay control, or NTC.
     */
    @XmlElement(name = "SampleId")
    String sampleId;

    /**
     * Optional Tube bar code of the tube (for example 2D bar code on the bottom
     * of the tube),
     */
    @XmlElement(name = "TubeBarcode")
    String tubeBarcode;

    /**
     * The kit bar code for the rack position, optional.
     */
    @XmlElement(name = "KitBarcode")
    String kitBarcode;

    /**
     * Name of the position (generated by QIAsymphony. May be left empty by
     * LIMS/user).
     */
    @XmlElement(name = "PositionName")
    String positionName;

    /**
     * Position on the rack (0-based index).
     */
    @XmlElement(name = "PositionIndex")
    String positionIndex;

    /**
     * Identification of the LiquidContainerType from QIAGEN labware file
     * (generated by QIAsymphony). May be left empty for LIMS/user created rack
     * files.
     */
    @XmlElement(name = "Labware")
    String labware;

    /**
     * Volume in the current rack position.
     */
    @XmlElement(name = "TotalVolumeInUl")
    String totalVolumeInUl;

    /**
     * Name of internal control, if any. Only used for eluate and assay racks.
     * Leave empty for sample racks.
     */
    @XmlElement(name = "InternalControlName")
    String internalControlName;

    /**
     * Internal parameter.
     */
    @XmlElement(name = "ICKitBarcode")
    String ICKitBarcode;

    /**
     * The validity of the current rack position.
     */
    @XmlElement(name = "State")
    String state;

    /**
     * Sample type. For “Sample” and “Eluate” only Sample, ExtractionControl_Pos
     * and ExtractionControl_Neg are permitted.
     */
    @XmlElement(name = "SampleType")
    String sampleType;

    /**
     * Optional concentration value for eluate racks in ng/μl
     */
    @XmlElement(name = "Concentration")
    String concentration;

    /**
     * Optionally indicates if the volume was changed by the user in the GUI
     * during ordering on AS.
     */
    @XmlElement(name = "EditedByUser")
    String editedByUser;
}
